import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppProvider from "../context/AppProvider";
import Header from "../common/components/base/Header";
import WrapFooter from "../common/components/base/Footer/WrapFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
        <body >
          
          <AppProvider>
            <Header />

            {children}
            <WrapFooter />
          </AppProvider>
          
        </body>
      
    </html>
  );
}
