export const LOGO = "/images/GoGroup-logo.png"
export const INTRO_IMAGE = "/images/Introduct-image.png"
export const CONTRACT_IMAGE = "/images/Contract-image.jpg"
export const FA_ICON = "/images/FA-icon.svg"
export const BANNER = ""
export const ICON_MENU = "/images/Icon-menu.svg"